# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
spec: src/**/*.spec.ts
extension:
- ts
reporter: min
require: ts-node/register
timeout: 3000 # For log upgrades.
watch: true
