name: Package
on: push

jobs:
    package:
        name: Package
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm install
                  npm install --force @microsoft/sarif-multitool-darwin @microsoft/sarif-multitool-win32
                  npx vsce package
            - uses: actions/upload-artifact@v1
              with:
                  path: sarif-vscode-0.0.0.vsix